In [3]:
pip install --upgrade mlxtend

Requirement already up-to-date: mlxtend in /usr/local/lib/python3.6/dist-packages (0.17.2)
Requirement already satisfied, skipping upgrade: matplotlib>=3.0.0 in /usr/local/lib/python3.6/dist-packages (from mlxtend) (3.2.1)
Requirement already satisfied, skipping upgrade: scikit-learn>=0.20.3 in /usr/local/lib/python3.6/dist-packages (from mlxtend) (0.22.2.post1)
Requirement already satisfied, skipping upgrade: scipy>=1.2.1 in /usr/local/lib/python3.6/dist-packages (from mlxtend) (1.4.1)
Requirement already satisfied, skipping upgrade: pandas>=0.24.2 in /usr/local/lib/python3.6/dist-packages (from mlxtend) (1.0.4)
Requirement already satisfied, skipping upgrade: numpy>=1.16.2 in /usr/local/lib/python3.6/dist-packages (from mlxtend) (1.18.4)
Requirement already satisfied, skipping upgrade: setuptools in /usr/local/lib/python3.6/dist-packages (from mlxtend) (47.1.1)
Requirement already satisfied, skipping upgrade: joblib>=0.13.2 in /usr/local/lib/python3.6/dist-packages (from mlxtend) (0.15.1)
Requirement already satisfied, skipping upgrade: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib>=3.0.0->mlxtend) (2.4.7)
Requirement already satisfied, skipping upgrade: cycler>=0.10 in /usr/local/lib/python3.6/dist-packages (from matplotlib>=3.0.0->mlxtend) (0.10.0)
Requirement already satisfied, skipping upgrade: kiwisolver>=1.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.2.0)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib>=3.0.0->mlxtend) (2.8.1)
Requirement already satisfied, skipping upgrade: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.24.2->mlxtend) (2018.9)
Requirement already satisfied, skipping upgrade: six in /usr/local/lib/python3.6/dist-packages (from cycler>=0.10->matplotlib>=3.0.0->mlxtend) (1.12.0)

In [0]:
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules, fpgrowth

In [0]:
#read the data
df = pd.read_csv('/content/drive/My Drive/Colab Notebooks/retail_dataset.csv')
df

          0       1       2       3       4       5       6
0     Bread    Wine    Eggs    Meat  Cheese  Pencil  Diaper
1     Bread  Cheese    Meat  Diaper    Wine    Milk  Pencil
2    Cheese    Meat    Eggs    Milk    Wine     NaN     NaN
3    Cheese    Meat    Eggs    Milk    Wine     NaN     NaN
4      Meat  Pencil    Wine     NaN     NaN     NaN     NaN
..      ...     ...     ...     ...     ...     ...     ...
310   Bread    Eggs  Cheese     NaN     NaN     NaN     NaN
311    Meat    Milk  Pencil     NaN     NaN     NaN     NaN
312   Bread  Cheese    Eggs    Meat  Pencil  Diaper    Wine
313    Meat  Cheese     NaN     NaN     NaN     NaN     NaN
314    Eggs    Wine   Bagel   Bread    Meat     NaN     NaN

[315 rows x 7 columns]

In [0]:
#find out how many unique items are actually there in the table
items = (df['0'].unique())
items

array(['Bread', 'Cheese', 'Meat', 'Eggs', 'Wine', 'Bagel', 'Pencil',
       'Diaper', 'Milk'], dtype=object)

In [0]:
#One Hot Encode the data
encoded_vals = []
for index, row in df.iterrows():
  labels = {}
  uncommons = list(set(items) - set(row))
  commons = list(set(items).intersection(row))
  for uc in uncommons:
    labels[uc] = 0
  for com in commons:
    labels[com] = 1
    encoded_vals.append(labels)
encoded_vals[0]

ohe_df = pd.DataFrame(encoded_vals)
ohe_df

      Milk  Bagel  Pencil  Cheese  Meat  Diaper  Wine  Eggs  Bread
0        0      0       1       1     1       1     1     1      1
1        0      0       1       1     1       1     1     1      1
2        0      0       1       1     1       1     1     1      1
3        0      0       1       1     1       1     1     1      1
4        0      0       1       1     1       1     1     1      1
...    ...    ...     ...     ...   ...     ...   ...   ...    ...
1272     0      1       0       0     1       0     1     1      1
1273     0      1       0       0     1       0     1     1      1
1274     0      1       0       0     1       0     1     1      1
1275     0      1       0       0     1       0     1     1      1
1276     0      1       0       0     1       0     1     1      1

[1277 rows x 9 columns]

In [0]:
#Applying Apriori
freq_items = apriori(ohe_df, min_support=0.2, use_colnames=True)
freq_items.head(7)

    support  itemsets
0  0.578700    (Milk)
1  0.488645   (Bagel)
2  0.445576  (Pencil)
3  0.624119  (Cheese)
4  0.574785    (Meat)
5  0.478465  (Diaper)
6  0.559906    (Wine)

In [0]:
#adjust the metric and min_threshold srguments
#eg.if you want to see rules which have a lift score of >=1.0
rules = association_rules(freq_items, metric="lift", min_threshold = 1.0)
rules.head()

  antecedents consequents  antecedent support  ...      lift  leverage  conviction
0    (Cheese)      (Milk)            0.624119  ...  1.084072  0.030365    1.130559
1      (Milk)    (Cheese)            0.578700  ...  1.084072  0.030365    1.162243
2      (Milk)      (Eggs)            0.578700  ...  1.063783  0.019626    1.078077
3      (Eggs)      (Milk)            0.531715  ...  1.063783  0.019626    1.096025
4      (Milk)     (Bread)            0.578700  ...  1.036344  0.012303    1.053990

[5 rows x 9 columns]

In [0]:
#FProwth
fpgrowth.fpgrowth(ohe_df, min_support=0.2, use_coluname=True)

TypeError: ignored